server:
  port: 7890

spring:
  profiles:
    active: sc

  #jdbc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: Dtj901213!

  #redis
  redis:
    password: ilove

mybatis-plus:
  type-handlers-package: com.love.ilove.handler
  configuration:
    # 3.0.8之前版本问题默认将枚举注册为EnumOrdinalTypeHandler,这是错误的方式,默认是 org.apache.ibatis.type.EnumTypeHandler
    # 如果项目之中实体统一使用IEnum或注解的方式,可配置成 com.baomidou.mybatisplus.extension.handlers.EnumTypeHandler,也可省略上面的type-enums-package配置
    # 配置type-enums-package只对注解方式的枚举处理能提前加载缓存.
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    banner: false

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 600 #JWT的超期限时间(60*60*24)
  jwtHead: Bearer  #JWT负载中拿到开头
  issUser: ilove #jwt 颁发者信息

qiniu:
  #  七牛云公共配置
  config:
    accessKey: 'xP26v6i5ZX5ricklajjShhW9Jjc20X-'
    secretKey: "YfDr4HEk9cgtjscKa7BgIbGvU6u5W79kNhJPVi0A"
  #  公开空间配置
  publicSpace:
    #    名称
    bucket: lovephoto
    #    绑定的域名
    url: 'http://psk85spi5.bkt.clouddn.com'
    #    限定用户上传的文件类型，限定多个以;分割，如：image/jpeg;image/png表示只允许上传jpg和png类型的图片
    mimeLimit:
      #      允许上传图片类型 image/* 表示允许上传所有图片类型，image/jpeg;image/png表示只允许上传jpg和png类型的图片.
      img:
        #        单位byte
        maxsize: 5242880 #5*1024*1024
        minsize:
      #      不允许上传的类型：!application/json;text/plain表示禁止上传json文本和纯文本。多项以;分割
      reject:

  #  私有空间配置
  securitySpace:
    bucket:
    url:
emai:
  userName: "jerry@mail.tianzijiaozi.top"
  protocol: "smtp"
  host: "smtp.exmail.qq.com"
  port: "465"
  isAuth: "true"
  usessl: "true"
#  fromUser: "iLove"
#  最大发送次数
  maxSendNum: 5
#  验证码最大校验次数
  maxCheckNum: 5
#  邮件验证码保留时间 单位：分钟
  keepMins: 120
