spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://tianzijiaozi.top:3306/ILove?useUnicode=true&characterEncoding=utf8

#redis
redis:
  host: tianzijiaozi.top

logging:
  level:
    com.love.iLove.handler: debug
